### ISSUE TITLE
Not updated for Firefox 37

### ISSUE THREAD

**Issue by ChimeraCoder** [tadast/Firefox-Hacker-News-plus-plus#1]
Cannot install this extension from the Firefox Add-ons marketplace on Firefox 37 for Android. This is likely a simple settings issue on the marketplace, in which case it may even be able to be fixed without re-uploading the app. 

![tmp_5445-screenshot_2015-05-15-22-06-14-1227390646](https://cloud.githubusercontent.com/assets/376414/7664300/a48e3454-fb4e-11e4-8721-a37b1ce41389.png)

**Comment by ChimeraCoder** [comment]
For what it's worth, Firefox 38 is the latest stable version, so it's probably worth updating the list of supported versions to include 38 as well.

**Comment by tadast** [comment]
I haven't changed anything, but it seems to be working now. Can you please re-open this issue if it's not the case? 
Thanks for reporting

**Comment by ChimeraCoder** [comment]
Still not working on Android, though I can install it on the desktop. The minimum version numbers for add-ons are separate for desktop and mobile, so it's possible that the requirements are set at 26+ for desktop but something else for Android.

**Comment by ChimeraCoder** [comment]
(also, I think only repository owners/collaborators can re-open issues once they're closed)
